version: '3.7'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '80:80'
    environment:
      - NODE_ENV=development